<a href="https://colab.research.google.com/github/VikasMishra30/python/blob/main/TF_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import tensorflow as tf

In [33]:
# Enable eager execution (if it's not already enabled)
tf.config.run_functions_eagerly(True)

In [34]:
tensor_zero_d = tf.constant(4, dtype=tf.float32)
print(tensor_zero_d)

tf.Tensor(4.0, shape=(), dtype=float32)


In [35]:
tensor_one_d = tf.constant([2, 0, -3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [36]:
tensor_two_d = tf.constant([[1, 2, 0],
                           [3, 5, -1],
                           [1, 5, 6],
                           [2, 3, 0]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  0]], shape=(4, 3), dtype=int32)


In [37]:
tensor_three_d = tf.constant([
    [
        [1, 2, 0],
        [3, 5, -1],
        [1, 5, 6],
        [2, 3, 0]
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  0]]

 [[ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]], shape=(2, 4, 3), dtype=int32)


In [38]:
print(tensor_three_d.ndim)

3


In [39]:
tensor_4D = tf.constant([
    [
        [
            [1, 2, 0],
            [3, 5, -1],
            [1, 5, 6],
            [2, 3, 0]
        ],
        [
            [7, 8, 9],
            [10, 11, 12],
            [13, 14, 15],
            [16, 17, 18]
        ]
    ],
    [
        [
            [19, 20, 21],
            [22, 23, 24],
            [25, 26, 27],
            [28, 29, 30]
        ],
        [
            [31, 32, 33],
            [34, 35, 36],
            [37, 38, 39],
            [40, 41, 42]
        ]
    ]
])

print(tensor_4D)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  0]]

  [[ 7  8  9]
   [10 11 12]
   [13 14 15]
   [16 17 18]]]


 [[[19 20 21]
   [22 23 24]
   [25 26 27]
   [28 29 30]]

  [[31 32 33]
   [34 35 36]
   [37 38 39]
   [40 41 42]]]], shape=(2, 2, 4, 3), dtype=int32)


In [40]:
tensor_1D = tf.constant([1, 0., -3], dtype = tf.float32)
print(tensor_1D)
casted_1D = tf.cast(tensor_1D, dtype = tf.int16)
print(casted_1D)
castedBool1D = tf.cast(tensor_1D, dtype = tf.bool)
print(castedBool1D)

tf.Tensor([ 1.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 1  0 -3], shape=(3,), dtype=int16)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [41]:
import numpy as np

In [42]:
np_array = np.array([1, 2, 4])
print(np_array)

convertedTensor = tf.convert_to_tensor(np_array)
print(convertedTensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [43]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[2, 2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]


 [[[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]

  [[1. 0. 0.]
   [0. 1. 0.]
   [0. 0. 1.]]]], shape=(2, 2, 3, 3), dtype=float32)


In [44]:
fill_tensor = tf.fill(
    [1, 2, 3], 7, name = None
)
print(fill_tensor)

tf.Tensor(
[[[7 7 7]
  [7 7 7]]], shape=(1, 2, 3), dtype=int32)


In [45]:
ones_tensor = tf.ones(
    [3, 3], dtype = tf.dtypes.float32, name = None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [46]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)


In [47]:
tf.rank(ones_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [48]:
tf.size(ones_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [49]:
 tf.size(ones_like_tensor, out_type = tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [50]:
random_tensor = tf.random.normal([3,2],
                                 mean = 0.0,
                                 stddev = 1.0,
                                 dtype = tf.dtypes.float32,
                                 seed = None, name = None)
print(random_tensor)

tf.Tensor(
[[ 1.5030582   0.06448315]
 [-1.8782123  -0.43845144]
 [-0.40295094  1.4476545 ]], shape=(3, 2), dtype=float32)


In [51]:
random_tensor = tf.random.uniform([5],
                                 minval = 0,
                                 maxval = 8,
                                 dtype = tf.dtypes.int32,
                                 seed = None, name = None)
print(random_tensor)

tf.Tensor([3 1 6 1 3], shape=(5,), dtype=int32)


In [52]:
tensor_indexed = tf.constant([3, 3, 2, 5, 7, 3, 10])
print(tensor_indexed[3])
print(tensor_indexed[0:4])
print(tensor_indexed[0:6:2])

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([3 3 2 5], shape=(4,), dtype=int32)
tf.Tensor([3 2 7], shape=(3,), dtype=int32)
