In [3]:
import tensorflow as tf
import numpy as np

In [4]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])

paddings = tf.constant([[1, 1,], [2, 2]])

tf.pad(t, paddings, "CONSTANT", constant_values=9)


<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 1, 2, 3, 9, 9],
       [9, 9, 4, 5, 6, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]], dtype=int32)>

In [5]:
params = tf.constant(["q", "w", "e", "r", "t", "y"])
params[1:3+1]

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'w', b'e', b'r'], dtype=object)>

In [6]:
tf.gather(params, [0, 1, 2])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'q', b'w', b'e'], dtype=object)>

In [7]:
indices = [[0, 1], [1, 0]]
params = [[1, 2], [3, 4], [5, 6]]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [8]:
  indices =[[[0, 1], [1, 0]],
            [[0, 0], [1, 1]]]
  params = tf.constant([[[1, 2], [3, 4], [5, 6]],
                        [[2, 5], [4, 7], [0, 9]]])
  tf.gather_nd(params, indices, batch_dims = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 7]], dtype=int32)>

In [9]:
x = [[1, 2, 0], [3, ], [1, 5, 6, 5, 6], [2, 3]]
x_ragged = tf.ragged.constant(x)
x_ragged

<tf.RaggedTensor [[1, 2, 0], [3], [1, 5, 6, 5, 6], [2, 3]]>

In [10]:
tf.ragged.boolean_mask(
    data = [[1, 3, 5], [2, 4, 6]],
    mask = [[True, False, True], [False, False, True]]
).to_list()

[[1, 5], [6]]

In [11]:
tf.RaggedTensor.from_row_lengths(
    values = [1, 2, 3, 4, 5, 6], # x = total values
    row_lengths = [2, 3, 0, 1, 0] # y = sum of all lengths
    # x == y
)

<tf.RaggedTensor [[1, 2], [3, 4, 5], [], [6], []]>

In [12]:
tf.RaggedTensor.from_row_limits(
    values = [1, 2, 3, 4, 5, 6],
    row_limits = [2, 2, 5, 6]
)

<tf.RaggedTensor [[1, 2], [], [3, 4, 5], [6]]>

In [13]:
tf.RaggedTensor.from_row_splits(
    values = [1, 2, 3, 4, 5, 6],
    row_splits = [0, 2, 2, 5, 6, 6]
)

<tf.RaggedTensor [[1, 2], [], [3, 4, 5], [6], []]>

In [14]:
y = tf.constant([[1, 2, 0], [3, 0, 0], [1, 5, 6], [2, 3, 2]])

tf.RaggedTensor.from_tensor(y, lengths = [1, 0, 2, 3])

<tf.RaggedTensor [[1], [], [1, 5], [2, 3, 2]]>

In [15]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1, 1], [2, 4]],
    values = [111, 224],
    dense_shape = [5, 7]
)

print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([111 224], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 7], shape=(2,), dtype=int64))


In [16]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 7), dtype=int32, numpy=
array([[  0,   0,   0,   0,   0,   0,   0],
       [  0, 111,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0, 224,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0]], dtype=int32)>

In [17]:
tensor_string = tf.constant(["hello", "world"])
print(tensor_string)

tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)


In [18]:
tf.strings.join(tensor_string, separator = " ")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [19]:
x = [[1, 2], [3, 4]]

x_var = tf.Variable(x, name = "var1")

"""
y_var = tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)
"""

print(x_var)

<tf.Variable 'var1:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [20]:
x_var.assign_sub([[1, 2], [-1, 1]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [4, 3]], dtype=int32)>

In [21]:
x_var.assign_add([[1, 2], [-1, 1]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
with tf.device("CPU:0"):
    x_1 = tf.Variable([1, 2, 3])
    x_2 = tf.Variable([4])

with tf.device("GPU:0"):
    x_3 = tf.Variable([1])
    x_4 = x_1 + x_2

print(x_1.device)
print(x_3.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
