In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x_abs = tf.constant([-2, 3, 4])
tf.abs(x_abs)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [ ]:
tf.abs(tf.constant(-0.2))

<tf.Tensor: shape=(), dtype=float32, numpy=0.2>

In [ ]:
x_complex = tf.constant([[-2.25 + 4.75j], [-3.25 + 5j]])
tf.abs(x_complex)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [5.96343022]])>

In [ ]:
tf.sqrt(-2.00**2 + 40.00**2)

<tf.Tensor: shape=(), dtype=float32, numpy=39.94997>

In [ ]:
x_1 = tf.constant([3, 4, 8])
x_2 = tf.constant([8, 6, 1])

print(tf.add(x_1, x_2))
print(tf.subtract(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))

tf.Tensor([11 10  9], shape=(3,), dtype=int32)
tf.Tensor([-5 -2  7], shape=(3,), dtype=int32)
tf.Tensor([24 24  8], shape=(3,), dtype=int32)
tf.Tensor([0.375      0.66666667 8.        ], shape=(3,), dtype=float64)


In [ ]:
x3_streched = tf.constant([3])
print(tf.math.add(x_1, x3_streched))

tf.Tensor([ 6  7 11], shape=(3,), dtype=int32)


In [ ]:
x1 = tf.constant([5, 3, 1, 4])
x2 = tf.constant([[1], [9], [8]])

print(tf.math.multiply(x1, x2))
x1 * x2

tf.Tensor(
[[ 5  3  1  4]
 [45 27  9 36]
 [40 24  8 32]], shape=(3, 4), dtype=int32)


<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 5,  3,  1,  4],
       [45, 27,  9, 36],
       [40, 24,  8, 32]], dtype=int32)>

In [ ]:
tf.math.maximum(x1, x2)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 3, 1, 4],
       [9, 9, 9, 9],
       [8, 8, 8, 8]], dtype=int32)>

In [ ]:
x = tf.constant([2, 30, 6])
print(tf.math.argmax(x))
print(tf.math.argmin(x))

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)


In [ ]:
x_arg = tf.constant([
    [2, 20, 30, 3, 6],
    [3, 11, 16, 1, 8],
    [14, 4, 32, 45, 27]
])
print(tf.math.argmax(x_arg, 0))
print(tf.math.argmax(x_arg, 1))

print(tf.math.argmin(x_arg, 0))
print(tf.math.argmin(x_arg, 1))

tf.Tensor([2 0 2 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 3], shape=(3,), dtype=int64)
tf.Tensor([0 2 1 1 0], shape=(5,), dtype=int64)
tf.Tensor([0 3 1], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 2]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 1],
       [3, 9]], dtype=int32)>

In [ ]:
tensor2d = tf.constant([
    [1, 2, 0],
    [1, 1, 3],
    [2, 5, 9]],
    dtype = tf.dtypes.float32)

In [ ]:
tf.math.reduce_sum(tensor2d, axis = None, keepdims = None, name = None)

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [ ]:
print(tf.math.reduce_max(tensor2d, axis = None, keepdims = None, name = None))
print(tf.math.reduce_min(tensor2d, axis = None, keepdims = None, name = None))
print(tf.math.reduce_mean(tensor2d, axis = None, keepdims = None, name = None))

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(2.6666667, shape=(), dtype=float32)


In [ ]:
print(tf.math.reduce_sum(tensor2d, axis = 0, keepdims = None, name = None))
print(tf.math.reduce_sum(tensor2d, axis = 1, keepdims = None, name = None))

tf.Tensor([ 4.  8. 12.], shape=(3,), dtype=float32)
tf.Tensor([ 3.  5. 16.], shape=(3,), dtype=float32)


In [ ]:
tf.math.top_k(tensor2d, k = 2)

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 1.],
       [3., 1.],
       [9., 5.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [2, 0],
       [2, 1]], dtype=int32)>)

In [ ]:
a = tf.constant([[1, 2, 3]])
b = tf.constant([[3], [2], [1]])

tf.linalg.matmul(
    a, b,
    transpose_a=False, transpose_b=False,
    adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False,
    output_type=None, name=None
)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[10]], dtype=int32)>

In [ ]:
tf.linalg.matmul(
    a, b,
    transpose_a=True, transpose_b=True,
    adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False,
    output_type=None, name=None
)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 2, 1],
       [6, 4, 2],
       [9, 6, 3]], dtype=int32)>

In [ ]:
b@a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]], dtype=int32)>

In [ ]:
tf.transpose(a)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]], dtype=int32)>

In [ ]:
c = tf.transpose(b@a)
print(c)

tf.Tensor(
[[3 2 1]
 [6 4 2]
 [9 6 3]], shape=(3, 3), dtype=int32)


In [ ]:
xj = tf.constant([[1 + 1j, 2 + 2j, 3 + 3j],
                 [4 + 4j, 5 + 5j, 6 + 6j]])
tf.linalg.adjoint(xj)

<tf.Tensor: shape=(3, 2), dtype=complex128, numpy=
array([[1.-1.j, 4.-4.j],
       [2.-2.j, 5.-5.j],
       [3.-3.j, 6.-6.j]])>

In [ ]:
xadj = tf.constant([[1, 3, 5], [0, 5, 9], [1, 4, 7]])
tf.linalg.adjoint(xadj)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 0, 1],
       [3, 5, 4],
       [5, 9, 7]], dtype=int32)>

In [ ]:
input = tf.constant([[1,  1,  2, 3],
                     [-1,  0,  1, 2],
                     [-2, -1,  5, 1],
                     [-3, -2, -1, 6]])
# in_band(m, n) = (num_lower < 0 || (m-n) <= num_lower)) && (num_upper < 0 || (n-m) <= num_upper)
tf.linalg.band_part(input, 1, -1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  1,  2,  3],
       [-1,  0,  1,  2],
       [ 0, -1,  5,  1],
       [ 0,  0, -1,  6]], dtype=int32)>

In [ ]:
tf.linalg.band_part(input, 0, -1) # Upper triangular part.

# tf.linalg.band_part(input, -1, 0) ==> Lower triangular part.
# tf.linalg.band_part(input, 0, 0) ==> Diagonal.

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 2, 3],
       [0, 0, 1, 2],
       [0, 0, 5, 1],
       [0, 0, 0, 6]], dtype=int32)>

In [ ]:
squareMatrix = tf.constant([[1, 2, 3],
                            [6, 9, 10],
                            [11, 63, 1]], dtype = tf.float32)

tf.linalg.inv(squareMatrix)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-1.4646227 ,  0.44103774, -0.01650945],
       [ 0.24528302, -0.0754717 ,  0.01886793],
       [ 0.6580189 , -0.09669813, -0.00707547]], dtype=float32)>

In [ ]:
s, u, v = tf.linalg.svd(squareMatrix)
print(s); print(u); print(v)

tf.Tensor([64.80807    11.025534    0.59338593], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.03505445  0.2646139  -0.9637173 ]
 [ 0.15973464  0.95042926  0.26677552]
 [ 0.98653746 -0.16329066 -0.00895122]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.18277623  0.37830296  0.90745777]
 [ 0.98227865 -0.10922081 -0.15231404]
 [ 0.04149249  0.91921574 -0.39156199]], shape=(3, 3), dtype=float32)


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7, 2], [6, 5, 9, 0], [3, 2, 0, 1]])

print(A.shape)
print(B.shape)

print("Matmul C = : \n")
print(np.matmul(A, B), "\n")

print("Einsum C = : \n")
print(np.einsum('ij,jk->ik', A, B), "\n")

(3, 3)
(3, 4)
Matmul C = : 

[[ 30  24  25   5]
 [ 84  69  73  14]
 [138 114 121  23]] 

Einsum C = : 

[[ 30  24  25   5]
 [ 84  69  73  14]
 [138 114 121  23]] 



In [ ]:
A = np.array([[1, 2, 3, 5], [4, 5, 6, 5], [7, 8, 9, 10]])
B = np.array([[9, 8, 7, 3], [6, 5, 9, 5], [3, 2, 0, 4]])

print(A.shape, B.shape)

print("Hardamard C = : \n")
print(A*B, "\n")

print("Einsum C = : \n")
print(np.einsum('ij,ij -> ij', A, B))

(3, 4) (3, 4)
Hardamard C = : 

[[ 9 16 21 15]
 [24 25 54 25]
 [21 16  0 40]] 

Einsum C = : 

[[ 9 16 21 15]
 [24 25 54 25]
 [21 16  0 40]]


In [ ]:
print(np.einsum('ij->ji', A))

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 5  5 10]]


In [ ]:
A3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
B3d = np.array([[[9, 8], [6, 4], [11, 1]], [[3, 2], [0, 1], [1, 2]]])

print(A3d.shape, B3d.shape)

print(np.einsum('bij, bjk-> bik', A3d, B3d))

(2, 2, 3) (2, 3, 2)
[[[ 54  19]
  [132  58]]

 [[ 30  40]
  [ 42  55]]]


In [ ]:
print(np.einsum('ij-> ', A))

65


In [ ]:
print(np.einsum('ij->j', A))
print(np.einsum('ij->i', A))

[12 15 18 20]
[11 20 34]


In [ ]:
# Q = batchsize, s_q, modelsize
# K = batchsize, s_k, modelsize

Q = np.random.randn(32, 64, 512)
K = np.random.randn(32, 128, 512)

np.einsum('bqm, bkm -> bqk', Q, K).shape

(32, 64, 128)

In [ ]:
A = np.random.randint(-100, 100, size=(2, 4, 4, 2)).astype(np.int32)
B = np.random.randint(-100, 100, size=(2, 4, 4, 1)).astype(np.int32)
print(A); print(B)
print("\n\n\n\n\n")
C = np.einsum('bcik, bcij -> bckj', B, A)
print(C.shape)
print(C)

[[[[  0  73]
   [ 99 -98]
   [ 82 -96]
   [ 52  16]]

  [[ 50 -86]
   [ -4 -84]
   [-63 -35]
   [ 43   5]]

  [[-43  57]
   [ 37  38]
   [-33  -1]
   [-17 -20]]

  [[ 37  30]
   [ 81  64]
   [-54 -50]
   [-71  34]]]


 [[[-15  86]
   [-24 -83]
   [ 99  68]
   [-99  94]]

  [[ 50  69]
   [-78  -5]
   [ 72 -37]
   [ 81  52]]

  [[-18 -64]
   [-73 -18]
   [  5 -15]
   [-62  33]]

  [[-68 -10]
   [ 86  72]
   [-86 -32]
   [ 16 -59]]]]
[[[[  91]
   [  57]
   [  -4]
   [ -46]]

  [[  23]
   [ -77]
   [  62]
   [  96]]

  [[ -64]
   [  47]
   [ -37]
   [  -8]]

  [[ -27]
   [  30]
   [  43]
   [ -75]]]


 [[[ -62]
   [  37]
   [  21]
   [ -70]]

  [[ -31]
   [ -31]
   [-100]
   [  60]]

  [[ -38]
   [  56]
   [ -26]
   [ -11]]

  [[  16]
   [  68]
   [ -48]
   [  27]]]]






(2, 4, 1, 2)
[[[[  2923    705]]

  [[  1680   2800]]

  [[  5848  -1665]]

  [[  4434  -3590]]]


 [[[  9051 -13555]]

  [[ -1472   4836]]

  [[ -2852   1451]]

  [[  9320   4679]]]]


In [ ]:
np.matmul(np.transpose(B, (0, 1, 3, 2)), A)

array([[[[  2923,    705]],

        [[  1680,   2800]],

        [[  5848,  -1665]],

        [[  4434,  -3590]]],


       [[[  9051, -13555]],

        [[ -1472,   4836]],

        [[ -2852,   1451]],

        [[  9320,   4679]]]], dtype=int32)

In [ ]:
print(B)
print(np.transpose(B, (0, 1, 3, 2)))

[[[[  91]
   [  57]
   [  -4]
   [ -46]]

  [[  23]
   [ -77]
   [  62]
   [  96]]

  [[ -64]
   [  47]
   [ -37]
   [  -8]]

  [[ -27]
   [  30]
   [  43]
   [ -75]]]


 [[[ -62]
   [  37]
   [  21]
   [ -70]]

  [[ -31]
   [ -31]
   [-100]
   [  60]]

  [[ -38]
   [  56]
   [ -26]
   [ -11]]

  [[  16]
   [  68]
   [ -48]
   [  27]]]]
[[[[  91   57   -4  -46]]

  [[  23  -77   62   96]]

  [[ -64   47  -37   -8]]

  [[ -27   30   43  -75]]]


 [[[ -62   37   21  -70]]

  [[ -31  -31 -100   60]]

  [[ -38   56  -26  -11]]

  [[  16   68  -48   27]]]]


In [ ]:
x = tf.constant([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(x.shape)
x_expand = tf.expand_dims(x, axis = 0)
print(x_expand.shape)
print(tf.expand_dims(x, 1).shape)
print(tf.expand_dims(x, 2).shape)

(2, 5)
(1, 2, 5)
(2, 1, 5)
(2, 5, 1)


In [ ]:
x_squeezed = tf.squeeze(x_expand)
print(tf.squeeze(x).shape)
print(x_squeezed.shape)

(2, 5)
(2, 5)


In [ ]:
x_reshape = tf.reshape(x_expand, [2, 5])
print(x_reshape.shape)

(2, 5)


In [ ]:
print(x, "\n\n")

print(tf.reshape(x, [-1]))
print(tf.reshape(x, [1, 10]))
print(tf.reshape(x, [10]))
print(tf.reshape(x, [5, 2]))
print(tf.reshape(x, [10, 1]))
#

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32) 


tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor([[ 1  2  3  4  5  6  7  8  9 10]], shape=(1, 10), dtype=int32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]], shape=(5, 2), dtype=int32)
tf.Tensor(
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]], shape=(10, 1), dtype=int32)


In [ ]:
t1 = [[1, 2, 3], [4, 5, 6]]
t2 = [[3, 5, 1], [3, 5, 2]]

print(tf.concat([t1, t2], axis = 0))
print(tf.concat([t1, t2], axis = 1))

print('\n')

print(tf.stack([t1, t2], axis = 0))
print(tf.stack([t1, t2], axis = 1))

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [3 5 1]
 [3 5 2]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[1 2 3 3 5 1]
 [4 5 6 3 5 2]], shape=(2, 6), dtype=int32)


tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[3 5 1]
  [3 5 2]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor(
[[[1 2 3]
  [3 5 1]]

 [[4 5 6]
  [3 5 2]]], shape=(2, 2, 3), dtype=int32)
